backend:
    name: git-gateway
    branch: main

media_folder: "assets/images"
public_folder: "/images"

slug:
  clean_accents: true

collections:
    - name: "uvod"
      label: "Úvod"
      folder: "content"
      fields:
        - { label: "Název", name: "title", widget: "string" }
        - { label: "Obsah", name: "body", widget: "markdown" }
      editor:
          preview: false

    - name: "kurzy"
      label: "Kurzy"
      folder: "content/kurzy"
      nested:
          depth: 2
      editor:
          preview: false
      fields:
          - { label: "Název", name: "title", widget: "string" }
          - { label: "Popis", name: "description", widget: "text", required: false }
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Pořadí", name: "weight", widget: "number" }
          - { label: "Obsah", name: "body", widget: "markdown" }

    - name: "sluzby"
      label: "Služby"
      folder: "content/sluzby"
      nested:
          depth: 2
      editor:
          preview: false
      fields:
          - { label: "Název", name: "title", widget: "string" }
          - { label: "Popis", name: "description", widget: "text", required: false }
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Pořadí", name: "weight", widget: "number" }
          - { label: "Obsah", name: "body", widget: "markdown" }

    - name: "nabor"
      label: "Nábor"
      folder: "content/nabor"
      nested:
          depth: 2
      editor:
          preview: false
      fields:
          - { label: "Název", name: "title", widget: "string" }
          - { label: "Popis", name: "description", widget: "text", required: false }
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Pořadí", name: "weight", widget: "number" }
          - { label: "Obsah", name: "body", widget: "markdown" }

    - name: "kontakt"
      label: "Kontakt"
      folder: "content/kontakt"
      editor:
          preview: false
      fields:
          - { label: "Název", name: "title", widget: "string" }
          - { label: "Popis", name: "description", widget: "text", required: false }
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Pořadí", name: "weight", widget: "number" }
          - { label: "Obsah", name: "body", widget: "markdown" }

    - name: "seznam-kurzu"
      label: "Seznam kurzů"
      label_singular: "course"
      folder: "data/courses"
      create: true
      extension: "yml"
      format: "yml"
      editor:
          preview: false
      fields:
          - { label: "Typ", name: "type", widget: "select", options: ["strelba", "taktika", "zdravoveda"] }
          - { label: "Název", name: "title", widget: "string" }
          - { label: "Popis", name: "description", widget: "text" }
          - { label: "Délka", name: "duration", widget: "number" }
          - { label: "Cena", name: "price", widget: "number" }
          - name: "participants"
            label: "Účastníků"
            widget: "object"
            fields: 
              - { label: "Minimum", name: "min", widget: "number", min: 1 }
              - { label: "Maximum", name: "max", widget: "number", min: 1, required: false }
          - name: "instructors"
            label: "Instruktoři"
            widget: "object"
            fields:
              - { label: "Minimum", name: "min", widget: "number", min: 1 }
              - { label: "Maximum", name: "max", widget: "number", min: 1, required: false }
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Úroveň", name: "level", widget: "number" }
          - { label: "Požadavky", name: "requirements", widget: "list", required: false }

    - name: "seznam-udalosti"
      label: "Seznam událostí"
      label_singular: "event"
      folder: "data/events"
      summary: "{{fields.time | date('d. M. YYYY')}} - {{fields.location}} - {{fields.type}}"
      slug: "{{fields.time | date('YYYY-MM-DD')}}-{{fields.type}}"
      create: true
      extension: "yml"
      format: "yml"
      editor:
          preview: false
      fields:
          - { label: "Typ", name: "type", widget: "relation", collection: "seznam-kurzu", value_field: "{{slug}}", search_fields: ["title"], display_fields: ["title"] }
          - { label: "Místo", name: "location", widget: "string" }
          - { label: "Datum", name: "time", widget: "datetime", date_format: "YYYY-MM-DD" }
          - { label: "Volná místa", name: "spots", widget: "number", min: 0 }
