backend:
    name: git-gateway
    branch: main

media_folder: "assets/images"
public_folder: "/images"

collections:
    - name: "pages"
      label: "Kurzy"
      folder: "content/kurzy"
      filter:
        field: "title"
        value: "Kurzy"
      create: true
      nested:
          depth: 2
          summary: "{{title}}"
      editor:
          preview: false
      fields:
          - { label: "Název", name: "title", widget: "string" }
          - { label: "Popis", name: "description", widget: "text" }
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Pořadí", name: "weight", widget: "number" }
          - { label: "Obsah", name: "body", widget: "markdown" }

    # - name: "courses"
    #   label: "Kurzy"
    #   folder: "content/kurzy/strelba"
    #   create: true
    #   filter: { field: "build.render", value: "never" }
    #   fields:
    #       - { label: "Typ", name: "type", widget: "string" }
    #       - { label: "Místo", name: "location", widget: "string" }
    #       - { label: "Datum", name: "time", widget: "datetime" }
    #       - { label: "Volná místa", name: "spots", widget: "number" }
    #       - name: "build"
    #         label: "Build Settings"
    #         widget: "object"
    #         fields:
    #             - {
    #                   label: "List",
    #                   name: "list",
    #                   widget: "hidden",
    #                   default: "always",
    #               }
    #             - {
    #                   label: "Render",
    #                   name: "render",
    #                   widget: "hidden",
    #                   default: "never",
    #               }

    - name: "course-types"
      label: "Typy kurzů"
      folder: "data/courses"
      create: true
      extension: "yml"
      format: "yml"
      nested:
          depth: 100
          summary: "{{title}}"
      editor:
          preview: false
      fields:
          - { label: "Název", name: "title", widget: "string" }
          - { label: "Popis", name: "description", widget: "text" }
          - { label: "Délka", name: "duration", widget: "number" }
          - { label: "Cena", name: "price", widget: "number" }
          - name: "participants"
            label: "Účastníků"
            widget: "object"
            fields:
              - { label: "Minimum", name: "min", widget: "number", min: 1 }
              - { label: "Maximum", name: "max", widget: "number", min: 1, required: false }
          - name: "instructors"
            label: "Instruktoři"
            widget: "object"
            fields:
              - { label: "Minimum", name: "min", widget: "number", min: 1 }
              - { label: "Maximum", name: "max", widget: "number", min: 1, required: false }
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Úroveň", name: "level", widget: "number" }
          - { label: "Požadavky", name: "requirements", widget: "list" }
